spring:
  datasource:
    username: root
    password:
    url: jdbc:mysql:///activiti-demo?useSSL=false&characterEncoding=utf8&serverTimezone=GMT%2B8
  jpa:
    database: mysql
    hibernate:
      ddl-auto: update
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  activiti:
    database-schema-update: true

site:
  ranks: ["员工", "部门经理", "总经理"]
